### ISSUE TITLE
MauticService pushForm returns value instead of bool 

### ISSUE THREAD

**Issue by ruudsilvrants** [mautic/mautic-typo3#10]
When performing a debug on the methode pushForm(), it doesn't return a boolean but a string like:
```<!DOCTYPE html> <html> 
<head> 
    <meta charset="UTF-8" /> 
    <meta http-equiv="refresh" content="1;url=http://my.domain"/>
    <title>Redirecting to http://my.domain</title>
</head>
 <body> Redirecting to <a href="http://my.domain">http://my.domain</a>. </body>
 </html>```

**Comment by Woeler** [comment]
The code never assumes it is a boolean per se, so I do not see the problem. The curl either holds the value of the response, or false in case of a time-out.

**Comment by ruudsilvrants** [comment]
/**
     * Push data to a Mautic form.
     *
     * @param array  $formStructure The data submitted by your form
     * @param string $mauticUrl     URL of the mautic installation
     * @param int    $formId        Mautic Form ID
     * @param string $ip            IP address of the lead
     *
     * @return bool
     */
    public function pushForm($formStructure, $mauticUrl, $formId, $ip = null)

See the function documentation above, as a return value you suggest that the return value is a boolean. Could you update the return value then?

**Comment by Woeler** [comment]
updated
