### ISSUE TITLE
Adding more elements like form/gatedvideo

### ISSUE THREAD

**Issue by josuavogel** [mautic/mautic-typo3#23]
If you look at other connectors (e.g. Mautic/WordPress) many additional use cases are implemented. Maybe we should add basic content elements to bind mautic elements into a website.
In the future we can improve step by step e.g. sync between elements and more.

**Comment by josuavogel** [comment]
I would like to include mautic-driven forms next. 

A simple approach would it be to add a minimal JS (see -> wordpress plugin).

What´s your opinion @Woeler?

**Comment by Woeler** [comment]
Sure, go for it.
