### ISSUE TITLE
Preview mode on disabled pages throw exception.

### ISSUE THREAD

**Issue by Atsyn** [mautic/mautic-typo3#32]
Administrators can view disabled pages in the preview mode, but your extension don't work in this mode.
This exception fully lock this mode!

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of Bitmotion\Mautic\Hooks\MauticTagHook::getPage() must be of the type array, boolean returned | TypeError thrown in file .../typo3conf/ext/mautic/Classes/Hooks/MauticTagHook.php in line 37.`

**Comment by Woeler** [comment]
Please specify what TYPO3 version this is in and what version of the extension you have installed.

**Comment by Woeler** [comment]
Newest 2.c version was just released. Should fix this.
