### ISSUE TITLE
Connection between TYPO3 and Mautic not working

### ISSUE THREAD

**Issue by danielkoch** [mautic/mautic-typo3#35]
I'm using TYPO3 9.x with the mautic extension (v3.x). On Mautic side I'm getting the following error:
```[2020-03-16 07:38:36] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\HttpException: "parameter_absent" at /vendor/willdurand/oauth-server-bundle/Service/OAuthServerService.php line 109 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\HttpException(code: 0): parameter_absent at /vendor/willdurand/oauth-server-bundle/Service/OAuthServerService.php:109)"} []```

**Comment by MincDev** [comment]
Hi @danielkoch 

I am getting the same error. Did you figure out what was causing this?

**Comment by danielkoch** [comment]
@MincDev: The behavior on my DEV and TEST system was relatively unstable and unexpected. At the end I managed to connected Mautic on my LIVE system. But the extension configuration is always reset (see also https://github.com/mautic/mautic-typo3/issues/33)
