### ISSUE TITLE
Mautic oauth v2 is not usable

### ISSUE THREAD

**Issue by maddy2101** [mautic/mautic-typo3#39]
I am using mautic 3.2.5 and want to use the oauth v2 version for communication. With this configured, the extension is not able to connect.

**To Reproduce**
Configure an oauth v2 credential pair in the extension and see how it does not connect.

**Expected behavior**
I want the connection to be made.

**Comment by tmaroschik** [comment]
Hey @maddy2101, I just provided a PR. Maybe you can check this out https://github.com/mautic/mautic-typo3/pull/44
