### ISSUE TITLE
Iframe same origin policy

### ISSUE THREAD

**Issue by Mainbird** [mautic/mautic-typo3#43]
Hi, 

we got some struggle with the same-origin policy. After clicking on the authorize button the iframe will be successfully rendered inside the TYPO3 backend, but the following lines will be written to the browser dev tools console:

```
Blocked autofocusing on a <input> element in a cross-origin subframe.
libraries.js?v80b9d231:366
Uncaught DOMException: Blocked a frame with origin "https://...." from accessing a cross-origin frame.
    at HTMLDocument.<anonymous> (https://..../media/js/app.js?v80b9d231:254:162)
    at mightThrow (https://..../media/js/libraries.js?v80b9d231:355:18)
    at process (https://..../media/js/libraries.js?v80b9d231:357:89)
```

So the authorization does not work, I can open the authorize button target in a new tab (outside of TYPO3), and then the authorization will work, but then TYPO3 will not get the requested OAuth token and the authorization will not work either.

So I think the mautic instance has to be on the same host as the TYPO3 instance or am I wrong? Or is there a way to change this?

**Comment by Moongazer** [comment]
@Mainbird can you confirm that this issue is obsolete using the newer versions? Because Authorize with OAuth2 will open a new window and not using the iframe anymore.

**Comment by Mainbird** [comment]
Hi @Moongazer,
sorry for my late response I am currently a bit busy, but I also unfortunately do not work on the project where this extension was installed anymore.

So I will close this issue now. :)
