### ISSUE TITLE
Compatible with TYPO3 11 

### ISSUE THREAD

**Issue by xbouillet** [mautic/mautic-typo3#55]
Hello,

**Is your feature request related to a problem? Please describe.**
This extension is not compatible with TYPO3 11

**Describe the solution you'd like**
A Version compatible with TYPO3 11

Thanks

**Comment by ekkeguembel** [comment]
On its way, please hold the line-
(If you need it urgently, feel free to sponsor :)

**Comment by xbouillet** [comment]
Hello,

We have downgraded TYPO3 to 10.4.23.
In composer.json, we have only the normal  TYPO3 lines and the line of mautic "" mautic / mautic-typo3 ":" 3.1.2 ""
 but when i lauch a composer update, I have a lot error.
For example :

```
- Conclusion: remove doctrine / dbal 2.13.3
    - typo3 / cms-core v9.5.23 requires doctrine / dbal ~ 2.10.0 || ~ 2.11.2 -> satisfiable by doctrine / dbal [2.10.2, 2.10.3, 2.10.4, 2.11.2, 2.11.3, v2.10.0, v2.10.1].
```

` typo3 / cms-core v9.5.12 conflicts with guzzlehttp / guzzle [6.5.5]`

`.- typo3 / cms-core v9.5.17 requires psr / log ~ 1.0.0 -> satisfiable by psr / log [1.0.0, 1.0.1, 1.0.2]`

`  - typo3 / cms-core v9.5.22 requires symfony / console ^ 4.1 -> satisfiable by symfony / console [v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3 , v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4 .2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3 , v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4 .4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.20, v4.4.21, v4.4.22, v4.4.23, v4.4.24, v4.4.25 , v4.4.26, v4.4.27, v4.4.29, v4.4.3, v4.4.30, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9].`

It's strange?
Must I downgrade all the packages in error?

Thanks a lot :)

**Comment by ekkeguembel** [comment]
uuh, I never tried a downgrade - sorry!

**Comment by sunzinet** [comment]
Is this still considered WIP / How can I view the state of the TYPO3 11 compatible release?
