### ISSUE TITLE
OAuth2 requestAccessToken() fails with 500 server error

### ISSUE THREAD

**Issue by Moongazer** [mautic/mautic-typo3#62]
**Describe the bug**
Connecting Mautic with the T3 plugin fails with a 500 server error, because the redirect response after OAuth-authorization is empty which the json_decode() method does not expect.

**To Reproduce**
1) In T3 backend module "API Connection", click button "Authorize with Mautic"

2) A new tab is opened requesting `https://mautic.ddev.site:444/oauth/v2/authorize?client_id=1_2...o40&redirect_uri=https%3A%2F%2Ft3backend.ddev.site%3A444%2Fmautic%2Fauthorize%2Feac...963&state=9fb...99f&scope=&response_type=code` which displays a Mautic page "The application TYPO3 DDEV would like to connect to your account." (TYPO3 DDEV is the name of my app added to Mautic)

3) Clicking the "Accept" button, a POST request is made to `https://mautic.ddev.site:444/oauth/v2/authorize
accepted=Accept&fos_oauth_server_authorize_form%5Bclient_id%5D=1_2...o40&fos_oauth_server_authorize_form%5Bresponse_type%5D=code&fos_oauth_server_authorize_form%5Bredirect_uri%5D=https%3A%2F%2Ft3backend.ddev.site%3A444%2Fmautic%2Fauthorize%2Fe...963&fos_oauth_server_authorize_form%5Bstate%5D=9fb...99f&fos_oauth_server_authorize_form%5Bscope%5D=`

4) The response of this POST request is a 302 redirect with location `https://t3backend.ddev.site:444/mautic/authorize/eac...963?state=9fb...99f&code=NmR...iNA`

5) T3 follows the redirect and opens GET `https://t3backend.ddev.site:444/mautic/authorize/eac...963?state=9fb...99f&code=NmR...iNA` which results in 
```
GuzzleHttp\Exception\InvalidArgumentException
json_decode error: Syntax error
in /var/www/html/vendor/guzzlehttp/guzzle/src/functions.php line 305
at GuzzleHttp\json_decode('', true)
in /var/www/html/public/typo3conf/ext/mautic/Classes/Middleware/AuthorizeMiddleware.php line 123
```

**Debugging**
After the redirect described in 5) EXT:mautic calls `Mautic\Auth\OAuth::validateAccessToken()` and tries to request an access token because non is found, by calling `Mautic\Auth\OAuth::requestAccessToken()`. This call should submit a request to `https://mautic.ddev.site:444/oauth/v2/token`, **but it is never received by the Mautic installation!** I added a breakpoint inside the AppKernel: the first request for authorization comes in, the second one (`https://mautic.ddev.site:444/oauth/v2/token`) not.

I could follow the request until `Mautic\Auth\AbstractAuth::makeRequest()` to line 181:
```
$response = new Response(curl_exec($curl), curl_getinfo($curl));
```
It seems that the cUrl request is never send (like I said, the breakpoint in Mautic Kernel is not hit), instead an empty response is created here with status-code 0 and empty body, which results in a `UnexpectedResponseFormatException` leading to the above JSON-decode exception.

In both apps, no log entries occur to help investigation.

**Additional context**
TYPO3 v10.4.28 (composer install)
EXT:marketing_automation v1.2.3 (composer install)
EXT:mautic: v4.1.0 (composer install)
Mautic v4.2.1 and also current v4.4.1 (Stable release from website)
PHP v7.4 + Apache2 in DDEV

**Maybe related**
- https://github.com/mautic/mautic-typo3/issues/56

**Comment by ekkeguembel** [comment]
Thanks for the good analysis. Investigating...

**Comment by Moongazer** [comment]
Great, please let me know if I can provide any further help, or if you need further details (in case you can't reproduce the issue or so).

**Comment by Moongazer** [comment]
**Update:**

An installation on "real" servers (not using DDEV) solved the issue. Not sure where the error exactly comes from, but here are some potential differences which might cause the above issue:

- Using virtualization container such as Docker/DDEV for TYPO3 and Mautic. During the OAuth2 process several security checks are made e.g. checking the URIs for allowed API access. It might happen that the hostname of a container is different from the value of its domain, which will result in an error.
- Using non-standard HTTP/S ports for the webserver, e.g. using a domain such as `https://my-typo3-project.ddev.site:444/` for the TYPO3 installation.

These are the main differences from my "real" installation which I can see. Maybe it will help someone else.

**Comment by Moongazer** [comment]
**Update 2:**

The final issue was that Curl could not reach the other DDEV container. That's why the Curl request never reached Mautic during the debugging session and just aborted without any visible error code. Configuring the internal Docker router solved the problem.

**Comment by ekkeguembel** [comment]
wow, thx so much @Moongazer - that explains :)

**Comment by KreativeKrise** [comment]
Thank you @Moongazer for that hint!

For anyone else looking for how to make different ddev projects communicate with each other, have a look at https://ddev.readthedocs.io/en/latest/users/usage/faq/#can-different-projects-communicate-with-each-other.

> Add a .ddev/docker-compose.communicate.yaml to project A to access project B via the official FQDN.
> ```
> services:
>   web:
>     external_links:
>       - "ddev-router:projectb.ddev.site"
> ```
