### ISSUE TITLE
Make DNC API available through ContactRepository

### ISSUE THREAD

**Issue by Moongazer** [mautic/mautic-typo3#69]
**Is your feature request related to a problem? Please describe.**
Currently it's only possible to set DNC options by providing an array for the payload of `createContact()` or `editContact()`, but not to unset (remove) these options:
```
            $contactData = [
               'doNotContact' = [
                    [
                        'reason' => 3,
                        'comments' => 'user',
                        'channel' => 'email',
                    ], [
                        'reason' => 3,
                        'comments' => 'user',
                        'channel' => 'sms',
                    ],
                ];
            ];
```

**Describe the solution you'd like**
The `ContactRepository` should implement the `addDnc()` and `removeDnc()` API calls, which would provide a cleaner way to handle DNC setting and un-setting.

**Describe alternatives you've considered**

**Additional context**

**Comment by ekkeguembel** [comment]
solved by https://github.com/mautic/mautic-typo3/pull/71
