### ISSUE TITLE
[FEATURE] Make it possible to set mautic api url for each form separate

### ISSUE THREAD

**Issue by frans-beech-it** [mautic/mautic-typo3#8]
For multi site's you want to be able to use multiple Mautic environments. For these situations it would be great if you could choose/set the Mautic url + credentials

**Comment by Woeler** [comment]
Things that need to be done to make this possible:

- [ ] Add Mautic URL to finisher setttings and finisher override
- [ ] Add Mautic credentials to finisher setttings and finisher override
- [ ] Add Mautic Form ID to finisher setttings and finisher override

**Comment by Mabahe** [comment]
IMO could be done simpler by using typoscript settings instead of TYPO3_CONF_VARS['EXT']['extConf'].
Every site could use its ts settings then.

**Comment by frans-beech-it** [comment]
@Mabahe and for the backend handling/form creation? There typoscript will not help will it?

**Comment by Mabahe** [comment]
I think the concept of the solr extension dealing with this very usefull also for your extension.
Saving the configurations related to the site root pages into the registry. You could grab them in FE and in BE context then.
