### ISSUE TITLE
[BUG] When Mautic doesn't respond correctly with a form id on first attempt form doesn't work 

### ISSUE THREAD

**Issue by frans-beech-it** [mautic/mautic-typo3#9]
When creating a new form via the BE form wizard of TYPO3 Mautic is asked for a form ID. But when this request somehow fails there is no retry after saving the form again.

Proposal: as long as there is no mautic ID in the YAML try to fetch a ID on saving the form in the TYPO3 BE

**Comment by Woeler** [comment]
Currently on hold until https://github.com/mautic/mautic/issues/4532 is fixed.
